### ISSUE TITLE
[Feature] Support Eip7594 blob format for tx build

### ISSUE THREAD

**Issue by mablr** [alloy-rs/alloy#3372]
### Component

rpc + consensus

### Describe the feature you would like

While `TransactionRequest` now supports both 4844 and 7594 sidecars since #3321
https://github.com/alloy-rs/alloy/blob/9a33f527d517e3784a288343f682e04ad3eda46d/crates/rpc-types-eth/src/transaction/request.rs#L136

Building tx request with 7594 blob format doesn't work for several reasons:
- Unconditional conversion to 4844 format, 7594 format blob is simply ignored.
https://github.com/alloy-rs/alloy/blob/9a33f527d517e3784a288343f682e04ad3eda46d/crates/rpc-types-eth/src/transaction/request.rs#L585-L590
- `TxEip4844Variant`'s generic default is 4844 format
https://github.com/alloy-rs/alloy/blob/9a33f527d517e3784a288343f682e04ad3eda46d/crates/consensus/src/transaction/eip4844.rs#L32
- And likewise for typed tx
https://github.com/alloy-rs/alloy/blob/9a33f527d517e3784a288343f682e04ad3eda46d/crates/consensus/src/transaction/typed.rs#L17

The fix seems quite straightforward -- change default generic types  to use `BlobTransactionSidecarVariant ` + fix build 4844 tx method -- but breaking.

Would it be acceptable do to it now ? If so i'd happy to make a PR 👍

This would also close https://github.com/alloy-rs/alloy/issues/2455, and unlock https://github.com/foundry-rs/foundry/issues/12449 and https://github.com/foundry-rs/foundry/issues/12222. Kinda related as well: https://github.com/alloy-rs/alloy/issues/3065

### Additional context

```rust 
// eip-7594 failure repro (based on existing test build_consensus_tx_works)
let sidecar = BlobTransactionSidecarEip7594::new(vec![Blob::repeat_byte(0xFA)], Vec::new(), Vec::new());
let eip4844_request = TransactionRequest {
    to: Some(TxKind::Call(Address::repeat_byte(0xDE))),
    max_fee_per_gas: Some(1234),
    max_priority_fee_per_gas: Some(678),
    nonce: Some(57),
    gas: Some(123456),
    max_fee_per_blob_gas: Some(13579),
    blob_versioned_hashes: Some(vec![B256::repeat_byte(0xAB)]),
    sidecar: Some(sidecar.into()),
    ..Default::default()
};

// this panics because EIP-7594 sidecar is ignored
eip4844_request.build_consensus_tx().unwrap();
```

**Comment by StackOverflowExcept1on** [comment]
I would also like to be able to do this on SolCallBuilder: https://github.com/alloy-rs/alloy/pull/3067#issuecomment-3669632876

**Comment by Evalir** [comment]
pretty sure this was solved by https://github.com/alloy-rs/alloy/pull/3321 ? cc @DaniPopes

**Comment by StackOverflowExcept1on** [comment]
@Evalir no, it's not solved. you still can't attach blob sidecar in new format to contract methods. see my prev comment.

**Comment by mablr** [comment]
@mattsse could you please reopen this issue, ref: https://github.com/alloy-rs/alloy/pull/3424#pullrequestreview-3620894339
